Document: scap-security-guide
Title: Debian scap-security-guide Manual
Author: <insert document author here>
Abstract: This manual describes what scap-security-guide is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/scap-security-guide/scap-security-guide.sgml.gz

Format: postscript
Files: /usr/share/doc/scap-security-guide/scap-security-guide.ps.gz

Format: text
Files: /usr/share/doc/scap-security-guide/scap-security-guide.text.gz

Format: HTML
Index: /usr/share/doc/scap-security-guide/html/index.html
Files: /usr/share/doc/scap-security-guide/html/*.html
